// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp7LtL9l9U12-GWtGC8gsP7j8gjNddtJU',
    appId: '1:174786591628:web:789b8404e5628710cc74a9',
    messagingSenderId: '174786591628',
    projectId: 'arogyaai-78b7a',
    authDomain: 'arogyaai-78b7a.firebaseapp.com',
    storageBucket: 'arogyaai-78b7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp7LtL9l9U12-GWtGC8gsP7j8gjNddtJU',
    appId: '1:174786591628:android:789b8404e5628710cc74a9',
    messagingSenderId: '174786591628',
    projectId: 'arogyaai-78b7a',
    storageBucket: 'arogyaai-78b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7LtL9l9U12-GWtGC8gsP7j8gjNddtJU',
    appId: '1:174786591628:ios:789b8404e5628710cc74a9',
    messagingSenderId: '174786591628',
    projectId: 'arogyaai-78b7a',
    storageBucket: 'arogyaai-78b7a.firebasestorage.app',
    iosBundleId: 'com.arogya.ai.arogya_ai',
  );
}
