import 'package:flutter/material.dart';
import 'package:animate_do/animate_do.dart';
import 'package:share_plus/share_plus.dart';
import '../services/api_service.dart';
import '../services/pdf_service.dart';

class HealthRecordsScreen extends StatefulWidget {
  const HealthRecordsScreen({super.key});

  @override
  State<HealthRecordsScreen> createState() => _HealthRecordsScreenState();
}

class _HealthRecordsScreenState extends State<HealthRecordsScreen> {
  List<dynamic> _reports = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadReports();
  }

  void _loadReports() async {
    setState(() => _isLoading = true);
    final history = await ApiService.getHistory();
    List<dynamic> reports = List.from(history);
    if (reports.isEmpty) {
      reports = [
        {
          'id': 'APT-781',
          'type': 'appointment',
          'token': 'TK-412',
          'patientName': ApiService.currentUser?['name'] ?? 'Arogya Patient',
          'doctorName': 'Dr. Priya Sharma',
          'clinicName': 'Primary Health Centre Medak',
          'hospitalName': 'Primary Health Centre Medak',
          'specialist': 'ENT Specialist',
          'symptoms': 'Throat soreness and difficulty swallowing',
          'date': '2026-08-22',
          'time': '10:30 AM',
          'status': 'Confirmed',
          'description': 'Confirmed appointment with Dr. Priya Sharma at Primary Health Centre Medak.'
        },
        {
          'id': 'rep-demo-1',
          'type': 'symptom',
          'condition': 'Viral Pharyngitis (Throat Infection)',
          'severity': 'medium',
          'specialist': 'ENT Specialist',
          'symptoms': 'Throat soreness and difficulty swallowing',
          'date': '2026-08-04',
          'description': 'Acute viral inflammation of the throat mucosa. Rest and warm salt gargle recommended.'
        }
      ];
    }
    setState(() {
      _reports = reports;
      _isLoading = false;
    });
  }

  void _exportRecord(Map<String, dynamic> report) {
    final text = """
=== AROGYAAI HEALTH DIAGNOSIS PASS ===
Patient: ${ApiService.currentUser?['name'] ?? 'Arogya User'}
Condition / Hospital: ${report['hospitalName'] ?? report['clinicName'] ?? report['condition'] ?? 'Health Pass'}
Doctor / Specialist: ${report['doctorName'] ?? report['specialist'] ?? 'General Physician'}
Symptoms Analyzed: "${report['symptoms'] ?? ''}"
Date Logged: ${report['date'] ?? ''} at ${report['time'] ?? ''}

DIAGNOSIS & NOTES:
${report['description'] ?? ''}

======================================
*This report is generated by ArogyaAI for clinical reference. Consult a real doctor before taking any critical medical decisions.*
""";
    
    Share.share(text, subject: 'ArogyaAI Health Record');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        title: const Text('Clinical Health Passes & Visits', style: TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF1E293B))),
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Color(0xFF1E293B)),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh, color: Color(0xFF10B981)),
            onPressed: _loadReports,
          )
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator(color: Color(0xFF10B981)))
          : _reports.isEmpty
              ? _buildEmptyState()
              : ListView.builder(
                  padding: const EdgeInsets.all(24),
                  itemCount: _reports.length,
                  itemBuilder: (context, index) {
                    final report = _reports[index];
                    final isAppointment = report['type'] == 'appointment' || report['hospitalName'] != null || report['doctorName'] != null;

                    final String title = isAppointment
                        ? (report['hospitalName'] ?? report['clinicName'] ?? report['condition'] ?? 'Hospital Visit Pass')
                        : (report['condition'] ?? 'AI Guidance Diagnosis Pass');

                    final String rawSym = report['symptoms']?.toString() ?? '';
                    final String symptomsText = (rawSym.isNotEmpty && rawSym != 'null')
                        ? rawSym
                        : (isAppointment ? 'Hospital Consultation Appointment' : 'General clinical assessment');

                    final String dateStr = report['date'] ?? report['appointmentDate'] ?? 'Scheduled Visit';
                    final String timeStr = report['time'] ?? report['appointmentTime'] ?? '';
                    final String displayDate = timeStr.isNotEmpty ? '$dateStr at $timeStr' : dateStr;

                    final String doctorName = report['doctorName'] ?? report['doctor'] ?? 'Doctor';
                    final String specialist = report['specialist'] ?? report['specialization'] ?? 'Specialist';
                    final String token = report['token'] ?? report['id'] ?? 'TK-101';
                    final String severity = report['severity'] ?? (isAppointment ? 'CONFIRMED' : 'medium');
                    final bool isHigh = severity.toString().toLowerCase() == 'high';

                    return FadeInUp(
                      child: Container(
                        margin: const EdgeInsets.only(bottom: 24),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(20),
                          boxShadow: [
                            BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 12, offset: const Offset(0, 4))
                          ],
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            // Header banner
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
                              decoration: BoxDecoration(
                                color: isAppointment
                                    ? const Color(0xFFDCFCE7)
                                    : (isHigh ? const Color(0xFFFEE2E2) : const Color(0xFFE0F2FE)),
                                borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
                              ),
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Row(
                                    children: [
                                      Icon(
                                        isAppointment ? Icons.local_hospital_rounded : Icons.health_and_safety_rounded,
                                        size: 16,
                                        color: isAppointment
                                            ? const Color(0xFF15803D)
                                            : (isHigh ? const Color(0xFFB91C1C) : const Color(0xFF0369A1)),
                                      ),
                                      const SizedBox(width: 6),
                                      Text(
                                        displayDate,
                                        style: TextStyle(
                                          color: isAppointment
                                              ? const Color(0xFF15803D)
                                              : (isHigh ? const Color(0xFFB91C1C) : const Color(0xFF0369A1)),
                                          fontWeight: FontWeight.bold,
                                          fontSize: 12,
                                        ),
                                      ),
                                    ],
                                  ),
                                  Container(
                                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                                    decoration: BoxDecoration(
                                      color: isAppointment
                                          ? const Color(0xFF10B981)
                                          : (isHigh ? const Color(0xFFEF4444) : const Color(0xFF0EA5E9)),
                                      borderRadius: BorderRadius.circular(20),
                                    ),
                                    child: Text(
                                      isAppointment ? 'TOKEN #$token' : severity.toString().toUpperCase(),
                                      style: const TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold),
                                    ),
                                  )
                                ],
                              ),
                            ),
                            
                            // Body content
                            Padding(
                              padding: const EdgeInsets.all(20),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    title,
                                    style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Color(0xFF1E293B)),
                                  ),
                                  const SizedBox(height: 6),
                                  if (isAppointment) ...[
                                    Row(
                                      children: [
                                        const Icon(Icons.person_outline_rounded, size: 14, color: Color(0xFF10B981)),
                                        const SizedBox(width: 4),
                                        Text(
                                          'Doctor: $doctorName ($specialist)',
                                          style: const TextStyle(fontWeight: FontWeight.w600, color: Color(0xFF334155), fontSize: 13),
                                        ),
                                      ],
                                    ),
                                    const SizedBox(height: 4),
                                  ],
                                  Text(
                                    'Symptoms / Problem: "$symptomsText"',
                                    style: TextStyle(fontStyle: FontStyle.italic, color: Colors.grey[700], fontSize: 13),
                                  ),
                                  const SizedBox(height: 12),
                                  Text(
                                    report['description'] ?? (isAppointment ? 'Appointment confirmed for clinical consultation.' : 'No clinical description available.'),
                                    style: const TextStyle(color: Color(0xFF475569), fontSize: 13, height: 1.4),
                                  ),
                                  const SizedBox(height: 16),
                                  
                                  // Action triggers
                                  Wrap(
                                    spacing: 8,
                                    runSpacing: 8,
                                    alignment: WrapAlignment.end,
                                    children: [
                                      OutlinedButton.icon(
                                        onPressed: () async {
                                          final pdfBytes = await PdfService.generatePrescriptionPdf(report);
                                          final filename = 'ArogyaAI_Prescription_${report['id'] ?? 'report'}.pdf';
                                          await PdfService.shareOrDownloadPdf(pdfBytes, filename);
                                        },
                                        icon: const Icon(Icons.picture_as_pdf, size: 16),
                                        label: const Text('Download PDF'),
                                        style: OutlinedButton.styleFrom(
                                          foregroundColor: const Color(0xFF0284C7),
                                          side: const BorderSide(color: Color(0xFF0284C7)),
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                        ),
                                      ),
                                      OutlinedButton.icon(
                                        onPressed: () async {
                                          final userEmail = ApiService.currentUser?['email'] ?? '';
                                          if (userEmail.isEmpty) {
                                            ScaffoldMessenger.of(context).showSnackBar(
                                              const SnackBar(content: Text('No email address linked to profile.')),
                                            );
                                            return;
                                          }
                                          ScaffoldMessenger.of(context).showSnackBar(
                                            const SnackBar(content: Text('Sending prescription email via Brevo...')),
                                          );
                                          final payload = {
                                            'patientEmail': userEmail,
                                            'patientName': ApiService.currentUser?['name'] ?? 'Patient',
                                            'condition': report['condition'],
                                            'symptoms': report['symptoms'],
                                            'medicines': report['medicines'],
                                            'diagnosisDate': report['date'],
                                          };
                                          final sent = await ApiService.sendPrescriptionEmail(payload);
                                          if (context.mounted) {
                                            ScaffoldMessenger.of(context).showSnackBar(
                                              SnackBar(
                                                content: Text(sent
                                                    ? 'Prescription email sent successfully!'
                                                    : 'Email sending attempted via Brevo.'),
                                                backgroundColor: sent ? const Color(0xFF10B981) : Colors.orange,
                                              ),
                                            );
                                          }
                                        },
                                        icon: const Icon(Icons.email, size: 16),
                                        label: const Text('Email Prescription'),
                                        style: OutlinedButton.styleFrom(
                                          foregroundColor: const Color(0xFF10B981),
                                          side: const BorderSide(color: Color(0xFF10B981)),
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                        ),
                                      ),
                                      OutlinedButton.icon(
                                        onPressed: () => _exportRecord(report),
                                        icon: const Icon(Icons.share, size: 16),
                                        label: const Text('Share'),
                                        style: OutlinedButton.styleFrom(
                                          foregroundColor: const Color(0xFF64748B),
                                          side: const BorderSide(color: Color(0xFFCBD5E1)),
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                        ),
                                      ),
                                    ],
                                  ),

                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.folder_open, size: 64, color: Colors.grey[300]),
          const SizedBox(height: 16),
          const Text('No clinical health records', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          const SizedBox(height: 8),
          const Text('Diagnose symptoms to generate active health passes', style: TextStyle(color: Colors.grey)),
        ],
      ),
    );
  }
}
