import 'package:flutter/material.dart';
import 'package:animate_do/animate_do.dart';
import 'package:share_plus/share_plus.dart';
import '../services/api_service.dart';

class HealthRecordsScreen extends StatefulWidget {
  const HealthRecordsScreen({super.key});

  @override
  State<HealthRecordsScreen> createState() => _HealthRecordsScreenState();
}

class _HealthRecordsScreenState extends State<HealthRecordsScreen> {
  List<dynamic> _reports = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadReports();
  }

  void _loadReports() async {
    setState(() => _isLoading = true);
    final history = await ApiService.getHistory();
    // Filter to only include diagnostic report logs
    setState(() {
      _reports = history.where((item) => item['type'] == 'symptom').toList();
      _isLoading = false;
    });
  }

  void _exportRecord(Map<String, dynamic> report) {
    final text = """
=== AROGYAAI HEALTH DIAGNOSIS PASS ===
Patient: ${ApiService.currentUser?['name'] ?? 'Arogya User'}
Condition: ${report['condition'] ?? 'Unknown'}
Severity: ${(report['severity'] ?? 'medium').toUpperCase()}
Specialist Rec: ${report['specialist'] ?? 'General Physician'}
Symptoms Analyzed: "${report['symptoms'] ?? ''}"
Date Logged: ${report['date'] ?? ''} at ${report['time'] ?? ''}

DIAGNOSIS DESCRIPTION:
${report['description'] ?? ''}

PRECAUTIONARY DIRECTIVES:
${(report['precautions'] as List? ?? []).map((p) => '- $p').join('\n')}

RECOMMENDED MEDICATIONS:
${(report['medicines'] as List? ?? []).map((m) => '- ${m['name']} (${m['instructions']})').join('\n')}

======================================
*This report is generated by ArogyaAI for clinical reference. Consult a real doctor before taking any critical medical decisions.*
""";
    
    Share.share(text, subject: 'ArogyaAI Health Diagnosis Record');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        title: const Text('Clinical Health Records', style: TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF1E293B))),
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Color(0xFF1E293B)),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh, color: Color(0xFF10B981)),
            onPressed: _loadReports,
          )
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator(color: Color(0xFF10B981)))
          : _reports.isEmpty
              ? _buildEmptyState()
              : ListView.builder(
                  padding: const EdgeInsets.all(24),
                  itemCount: _reports.length,
                  itemBuilder: (context, index) {
                    final report = _reports[index];
                    final condition = report['condition'] ?? 'Diagnosis Report';
                    final date = report['date'] ?? 'Just Now';
                    final severity = report['severity'] ?? 'medium';
                    final isHigh = severity.toString().toLowerCase() == 'high';

                    return FadeInUp(
                      child: Container(
                        margin: const EdgeInsets.only(bottom: 24),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(20),
                          boxShadow: [
                            BoxShadow(color: Colors.black.withOpacity(0.02), blurRadius: 10, offset: const Offset(0, 4))
                          ],
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            // Header banner
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
                              decoration: BoxDecoration(
                                color: isHigh ? const Color(0xFFFEE2E2) : const Color(0xFFE0F2FE),
                                borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
                              ),
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    date,
                                    style: TextStyle(
                                      color: isHigh ? const Color(0xFFB91C1C) : const Color(0xFF0369A1),
                                      fontWeight: FontWeight.bold,
                                      fontSize: 12,
                                    ),
                                  ),
                                  Container(
                                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                                    decoration: BoxDecoration(
                                      color: isHigh ? const Color(0xFFEF4444) : const Color(0xFF0EA5E9),
                                      borderRadius: BorderRadius.circular(20),
                                    ),
                                    child: Text(
                                      severity.toString().toUpperCase(),
                                      style: const TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold),
                                    ),
                                  )
                                ],
                              ),
                            ),
                            
                            // Body content
                            Padding(
                              padding: const EdgeInsets.all(20),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    condition,
                                    style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Color(0xFF1E293B)),
                                  ),
                                  const SizedBox(height: 4),
                                  Text(
                                    'Symptoms: "${report['symptoms']}"',
                                    style: TextStyle(fontStyle: FontStyle.italic, color: Colors.grey[600], fontSize: 13),
                                  ),
                                  const SizedBox(height: 12),
                                  Text(
                                    report['description'] ?? 'No clinical description available.',
                                    style: const TextStyle(color: Color(0xFF475569), fontSize: 13, height: 1.4),
                                  ),
                                  const SizedBox(height: 16),
                                  
                                  // Action triggers
                                  Row(
                                    mainAxisAlignment: MainAxisAlignment.end,
                                    children: [
                                      OutlinedButton.icon(
                                        onPressed: () => _exportRecord(report),
                                        icon: const Icon(Icons.share, size: 16),
                                        label: const Text('Export/Share Report'),
                                        style: OutlinedButton.styleFrom(
                                          foregroundColor: const Color(0xFF10B981),
                                          side: const BorderSide(color: Color(0xFF10B981)),
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.folder_open, size: 64, color: Colors.grey[300]),
          const SizedBox(height: 16),
          const Text('No clinical health records', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          const SizedBox(height: 8),
          const Text('Diagnose symptoms to generate active health passes', style: TextStyle(color: Colors.grey)),
        ],
      ),
    );
  }
}
